-- Run this once in the Supabase SQL editor for project ucvsnxexmvxpccyatmmk.
-- Backfills available_autoparts/available_scrapyard (sql/038) from the real
-- source data behind sql/033's pricing import (Mechanc_Items.csv's own `store`
-- column) -- this was sitting right there in the original import, just never
-- carried into the new columns. Matched by name, case-insensitively, same as
-- sql/033 itself. 481 of 481 source rows have a usable store value.
--
-- No purchase_cost changes needed: every one of the 26 items sold at both
-- stores has a LOWER Autoparts price than Scrapyard in the source data (no
-- exceptions), and sql/033 already always kept the Autoparts price for those --
-- so "always use the cheaper one" was already true, just needed asking to
-- confirm rather than assume.

update catalogue_items ci set
  available_autoparts = v.auto,
  available_scrapyard = v.scrap
from (values
  ('Aircraft Engine', true, false),
  ('Aircraft Tire', true, false),
  ('Landing Strut', true, false),
  ('Body Filler', false, true),
  ('Body Patch', false, true),
  ('Exterior Cosmetics', true, false),
  ('Fiberglass Sheet', false, true),
  ('Front Fender', false, true),
  ('Hood', false, true),
  ('Rear Fender', false, true),
  ('Trunk Lid', false, true),
  ('Vehicle Exhaust', true, false),
  ('Vehicle Extra Part', true, false),
  ('Vehicle Extras', true, false),
  ('Vehicle Front Bumper', true, false),
  ('Vehicle Grille', true, false),
  ('Vehicle Rear Bumper', true, false),
  ('Vehicle Roof', true, false),
  ('Vehicle Skirts', true, false),
  ('Vehicle Spoiler', true, false),
  ('Brake Pads', true, false),
  ('Brake Replacement', true, false),
  ('Brake Rotor', false, true),
  ('Brake Upgrade', true, false),
  ('Race Brake Pads', false, true),
  ('Sport Brake Pads', false, true),
  ('Stock Brake Pads', false, true),
  ('Street Brake Pads', false, true),
  ('Performance Camshaft', true, false),
  ('Race Camshaft', true, false),
  ('Stock/Mild Camshaft', true, false),
  ('Street Perf Camshaft', true, false),
  ('Torque/Tow Camshaft', true, false),
  ('H-Beam Billet Aluminum Connecting Rod', true, false),
  ('H-Beam Billet Steel Connecting Rod', true, false),
  ('H-Beam Cast Aluminum Connecting Rod', false, true),
  ('H-Beam Cast Iron Connecting Rod', false, true),
  ('H-Beam Cast Steel Connecting Rod', false, true),
  ('H-Beam Forged Aluminum Connecting Rod', true, false),
  ('H-Beam Forged Steel Connecting Rod', true, false),
  ('H-Beam Powder Metal Connecting Rod', true, false),
  ('H-Beam Titanium Connecting Rod', true, false),
  ('I-Beam Billet Aluminum Connecting Rod', true, false),
  ('I-Beam Billet Steel Connecting Rod', true, false),
  ('I-Beam Cast Aluminum Connecting Rod', false, true),
  ('I-Beam Cast Iron Connecting Rod', false, true),
  ('I-Beam Cast Steel Connecting Rod', false, true),
  ('I-Beam Forged Aluminum Connecting Rod', true, false),
  ('I-Beam Forged Steel Connecting Rod', true, false),
  ('I-Beam Powder Metal Connecting Rod', true, false),
  ('I-Beam Titanium Connecting Rod', true, false),
  ('X-Beam Billet Aluminum Connecting Rod', true, false),
  ('X-Beam Billet Steel Connecting Rod', true, false),
  ('X-Beam Cast Aluminum Connecting Rod', false, true),
  ('X-Beam Cast Iron Connecting Rod', false, true),
  ('X-Beam Cast Steel Connecting Rod', false, true),
  ('X-Beam Forged Aluminum Connecting Rod', true, false),
  ('X-Beam Forged Steel Connecting Rod', true, false),
  ('X-Beam Powder Metal Connecting Rod', true, false),
  ('X-Beam Titanium Connecting Rod', true, false),
  ('Battery Coolant', true, false),
  ('Race Radiator', true, false),
  ('Sport Radiator', true, false),
  ('Street Radiator', true, false),
  ('Billet Crankshaft', true, false),
  ('Cast Crankshaft', false, true),
  ('Forged Crankshaft', true, false),
  ('Factory Cast Aluminum Cylinder Head', false, true),
  ('Factory Cast Iron Cylinder Head', false, true),
  ('Factory Cast Steel Cylinder Head', false, true),
  ('Factory Forged Aluminum Cylinder Head', true, false),
  ('Factory Forged Steel Cylinder Head', true, false),
  ('Ported & Polished Cast Aluminum Cylinder Head', true, false),
  ('Ported & Polished Cast Iron Cylinder Head', true, false),
  ('Ported & Polished Cast Steel Cylinder Head', true, false),
  ('Ported & Polished Forged Aluminum Cylinder Head', true, false),
  ('Ported & Polished Forged Steel Cylinder Head', true, false),
  ('4WD Conversion Kit', true, false),
  ('AWD Conversion Kit', true, false),
  ('Differential Re-Gear Kit', true, false),
  ('Drive Train Pump', true, false),
  ('Drivetrain Fluid', true, true),
  ('Drivetrain Part', true, false),
  ('FWD Conversion Kit', true, false),
  ('RWD Conversion Kit', true, false),
  ('EV Battery', true, false),
  ('EV Drive Motor', true, false),
  ('EV Power Inverter', true, false),
  ('EV Traction Battery', true, false),
  ('Air Filter', true, true),
  ('Copper Standard Spark Plug', false, true),
  ('Head Gasket Set', true, false),
  ('Iridium Spark Plug', false, true),
  ('Platinum Spark Plug', false, true),
  ('Spark Plugs', true, false),
  ('Aluminum-Tin Conrod Bearing', false, true),
  ('Aluminum-Tin Main Bearing', false, true),
  ('Bi-Metal Race Conrod Bearing', false, true),
  ('Bi-Metal Race Main Bearing', false, true),
  ('Tri-Metal Conrod Bearing', false, true),
  ('Tri-Metal Main Bearing', false, true),
  ('Billet Aluminum Flat 2 Engine Block', true, false),
  ('Billet Aluminum Flat 4 Engine Block', true, false),
  ('Billet Aluminum Flat 6 Engine Block', true, false),
  ('Billet Aluminum Flat 8 Engine Block', true, false),
  ('Billet Aluminum Inline 3 Engine Block', true, false),
  ('Billet Aluminum Inline 4 Engine Block', true, false),
  ('Billet Aluminum Inline 5 Engine Block', true, false),
  ('Billet Aluminum Inline 6 Engine Block', true, false),
  ('Billet Aluminum Inline 8 Engine Block', true, false),
  ('Billet Aluminum L4 Engine Block', true, false),
  ('Billet Aluminum Single Piston Engine Block', true, false),
  ('Billet Aluminum V-Twin Engine Block', true, false),
  ('Billet Aluminum V10 Engine Block', true, false),
  ('Billet Aluminum V12 Engine Block', true, false),
  ('Billet Aluminum V16 Engine Block', true, false),
  ('Billet Aluminum V4 Engine Block', true, false),
  ('Billet Aluminum V6 Engine Block', true, false),
  ('Billet Aluminum V8 Engine Block', true, false),
  ('Billet Aluminum W12 Engine Block', true, false),
  ('Billet Aluminum W16 Engine Block', true, false),
  ('Billet Aluminum W18 Engine Block', true, false),
  ('Billet Aluminum W6 Engine Block', true, false),
  ('Billet Aluminum W8 Engine Block', true, false),
  ('Billet Steel Flat 2 Engine Block', true, false),
  ('Billet Steel Flat 4 Engine Block', true, false),
  ('Billet Steel Flat 6 Engine Block', true, false),
  ('Billet Steel Flat 8 Engine Block', true, false),
  ('Billet Steel Inline 3 Engine Block', true, false),
  ('Billet Steel Inline 4 Engine Block', true, false),
  ('Billet Steel Inline 5 Engine Block', true, false),
  ('Billet Steel Inline 6 Engine Block', true, false),
  ('Billet Steel Inline 8 Engine Block', true, false),
  ('Billet Steel L4 Engine Block', true, false),
  ('Billet Steel Single Piston Engine Block', true, false),
  ('Billet Steel V-Twin Engine Block', true, false),
  ('Billet Steel V10 Engine Block', true, false),
  ('Billet Steel V12 Engine Block', true, false),
  ('Billet Steel V16 Engine Block', true, false),
  ('Billet Steel V4 Engine Block', true, false),
  ('Billet Steel V6 Engine Block', true, false),
  ('Billet Steel V8 Engine Block', true, false),
  ('Billet Steel W12 Engine Block', true, false),
  ('Billet Steel W16 Engine Block', true, false),
  ('Billet Steel W18 Engine Block', true, false),
  ('Billet Steel W6 Engine Block', true, false),
  ('Billet Steel W8 Engine Block', true, false),
  ('Cast Aluminum Flat 2 Engine Block', false, true),
  ('Cast Aluminum Flat 4 Engine Block', false, true),
  ('Cast Aluminum Flat 6 Engine Block', false, true),
  ('Cast Aluminum Flat 8 Engine Block', false, true),
  ('Cast Aluminum Inline 3 Engine Block', false, true),
  ('Cast Aluminum Inline 4 Engine Block', false, true),
  ('Cast Aluminum Inline 5 Engine Block', false, true),
  ('Cast Aluminum Inline 6 Engine Block', false, true),
  ('Cast Aluminum Inline 8 Engine Block', false, true),
  ('Cast Aluminum L4 Engine Block', false, true),
  ('Cast Aluminum Single Piston Engine Block', false, true),
  ('Cast Aluminum V-Twin Engine Block', false, true),
  ('Cast Aluminum V10 Engine Block', false, true),
  ('Cast Aluminum V12 Engine Block', false, true),
  ('Cast Aluminum V16 Engine Block', false, true),
  ('Cast Aluminum V4 Engine Block', false, true),
  ('Cast Aluminum V6 Engine Block', false, true),
  ('Cast Aluminum V8 Engine Block', false, true),
  ('Cast Aluminum W12 Engine Block', false, true),
  ('Cast Aluminum W16 Engine Block', false, true),
  ('Cast Aluminum W18 Engine Block', false, true),
  ('Cast Aluminum W6 Engine Block', false, true),
  ('Cast Aluminum W8 Engine Block', false, true),
  ('Cast Iron Flat 2 Engine Block', false, true),
  ('Cast Iron Flat 4 Engine Block', false, true),
  ('Cast Iron Flat 6 Engine Block', false, true),
  ('Cast Iron Flat 8 Engine Block', false, true),
  ('Cast Iron Inline 3 Engine Block', false, true),
  ('Cast Iron Inline 4 Engine Block', false, true),
  ('Cast Iron Inline 5 Engine Block', false, true),
  ('Cast Iron Inline 6 Engine Block', false, true),
  ('Cast Iron Inline 8 Engine Block', false, true),
  ('Cast Iron L4 Engine Block', false, true),
  ('Cast Iron Single Piston Engine Block', false, true),
  ('Cast Iron V-Twin Engine Block', false, true),
  ('Cast Iron V10 Engine Block', false, true),
  ('Cast Iron V12 Engine Block', false, true),
  ('Cast Iron V16 Engine Block', false, true),
  ('Cast Iron V4 Engine Block', false, true),
  ('Cast Iron V6 Engine Block', false, true),
  ('Cast Iron V8 Engine Block', false, true),
  ('Cast Iron W12 Engine Block', false, true),
  ('Cast Iron W16 Engine Block', false, true),
  ('Cast Iron W18 Engine Block', false, true),
  ('Cast Iron W6 Engine Block', false, true),
  ('Cast Iron W8 Engine Block', false, true),
  ('Compacted Graphite Iron Flat 2 Engine Block', true, false),
  ('Compacted Graphite Iron Flat 4 Engine Block', true, false),
  ('Compacted Graphite Iron Flat 6 Engine Block', true, false),
  ('Compacted Graphite Iron Flat 8 Engine Block', true, false),
  ('Compacted Graphite Iron Inline 3 Engine Block', true, false),
  ('Compacted Graphite Iron Inline 4 Engine Block', true, false),
  ('Compacted Graphite Iron Inline 5 Engine Block', true, false),
  ('Compacted Graphite Iron Inline 6 Engine Block', true, false),
  ('Compacted Graphite Iron Inline 8 Engine Block', true, false),
  ('Compacted Graphite Iron L4 Engine Block', true, false),
  ('Compacted Graphite Iron Single Piston Engine Block', true, false),
  ('Compacted Graphite Iron V-Twin Engine Block', true, false),
  ('Compacted Graphite Iron V10 Engine Block', true, false),
  ('Compacted Graphite Iron V12 Engine Block', true, false),
  ('Compacted Graphite Iron V16 Engine Block', true, false),
  ('Compacted Graphite Iron V4 Engine Block', true, false),
  ('Compacted Graphite Iron V6 Engine Block', true, false),
  ('Compacted Graphite Iron V8 Engine Block', true, false),
  ('Compacted Graphite Iron W12 Engine Block', true, false),
  ('Compacted Graphite Iron W16 Engine Block', true, false),
  ('Compacted Graphite Iron W18 Engine Block', true, false),
  ('Compacted Graphite Iron W6 Engine Block', true, false),
  ('Compacted Graphite Iron W8 Engine Block', true, false),
  ('Magnesium Alloy Flat 2 Engine Block', true, false),
  ('Magnesium Alloy Flat 4 Engine Block', true, false),
  ('Magnesium Alloy Flat 6 Engine Block', true, false),
  ('Magnesium Alloy Flat 8 Engine Block', true, false),
  ('Magnesium Alloy Inline 3 Engine Block', true, false),
  ('Magnesium Alloy Inline 4 Engine Block', true, false),
  ('Magnesium Alloy Inline 5 Engine Block', true, false),
  ('Magnesium Alloy Inline 6 Engine Block', true, false),
  ('Magnesium Alloy Inline 8 Engine Block', true, false),
  ('Magnesium Alloy L4 Engine Block', true, false),
  ('Magnesium Alloy Single Piston Engine Block', true, false),
  ('Magnesium Alloy V-Twin Engine Block', true, false),
  ('Magnesium Alloy V10 Engine Block', true, false),
  ('Magnesium Alloy V12 Engine Block', true, false),
  ('Magnesium Alloy V16 Engine Block', true, false),
  ('Magnesium Alloy V4 Engine Block', true, false),
  ('Magnesium Alloy V6 Engine Block', true, false),
  ('Magnesium Alloy V8 Engine Block', true, false),
  ('Magnesium Alloy W12 Engine Block', true, false),
  ('Magnesium Alloy W16 Engine Block', true, false),
  ('Magnesium Alloy W18 Engine Block', true, false),
  ('Magnesium Alloy W6 Engine Block', true, false),
  ('Magnesium Alloy W8 Engine Block', true, false),
  ('Anti-Lag System Kit', true, false),
  ('Boost Controller', true, false),
  ('Large Centrifugal Supercharger', true, false),
  ('Large Positive Displacement Supercharger', true, false),
  ('Medium Centrifugal Supercharger', true, false),
  ('Medium Positive Displacement Supercharger', true, false),
  ('Nitrous Bottle (Refill)', true, false),
  ('Nitrous Install Kit', true, false),
  ('Nitrous Kit - 100 Shot', true, false),
  ('Nitrous Kit - 200 Shot', true, false),
  ('Nitrous Kit - 300 Shot', true, false),
  ('Nitrous Kit - 50 Shot', true, false),
  ('Race Intercooler', true, false),
  ('Small Centrifugal Supercharger', true, false),
  ('Small Positive Displacement Supercharger', true, false),
  ('Stock Intercooler', true, false),
  ('Street Intercooler', true, false),
  ('Supercharger Turbo', true, false),
  ('Turbocharger - Large Compressor / Large Turbine', true, false),
  ('Turbocharger - Large Compressor / Medium Turbine', true, false),
  ('Turbocharger - Large Compressor / Small Turbine', true, false),
  ('Turbocharger - Medium Compressor / Large Turbine', true, false),
  ('Turbocharger - Medium Compressor / Medium Turbine', true, false),
  ('Turbocharger - Medium Compressor / Small Turbine', true, false),
  ('Turbocharger - Small Compressor / Large Turbine', true, false),
  ('Turbocharger - Small Compressor / Medium Turbine', true, false),
  ('Turbocharger - Small Compressor / Small Turbine', true, false),
  ('Window Part', false, true),
  ('Window Tint Kit', true, false),
  ('glass', false, true),
  ('Carplay Installer Tool', true, false),
  ('Custom Vehicle Horn', true, false),
  ('Internal Cosmetics', true, false),
  ('Mechanic Tablet', true, true),
  ('Seat Cosmetics', true, false),
  ('Subwoofer', true, false),
  ('Taillight Assembly', false, true),
  ('Underglow LEDS', true, false),
  ('Xenon Headlights', true, true),
  ('Customized Plates', true, false),
  ('Decal Remover', true, false),
  ('Livery Roll', true, false),
  ('Vehicle Spray Can', true, false),
  ('Vehicle Wax Kit', true, true),
  ('Cast Iron (Standard) Ring Pack', false, true),
  ('Moly-Coated Race Ring Pack', false, true),
  ('Steel Performance Ring Pack', false, true),
  ('Dished Billet Aluminum Piston', true, false),
  ('Dished Billet Steel Piston', true, false),
  ('Dished Cast Aluminum Piston', false, true),
  ('Dished Cast Iron Piston', false, true),
  ('Dished Cast Steel Piston', false, true),
  ('Dished Forged Aluminum Piston', true, false),
  ('Dished Forged Steel Piston', true, false),
  ('Dished Powder Metal Piston', true, false),
  ('Dished Titanium Piston', true, false),
  ('Domed Billet Aluminum Piston', true, false),
  ('Domed Billet Steel Piston', true, false),
  ('Domed Cast Aluminum Piston', false, true),
  ('Domed Cast Iron Piston', false, true),
  ('Domed Cast Steel Piston', false, true),
  ('Domed Forged Aluminum Piston', true, false),
  ('Domed Forged Steel Piston', true, false),
  ('Domed Powder Metal Piston', true, false),
  ('Domed Titanium Piston', true, false),
  ('Flat Top Billet Aluminum Piston', true, false),
  ('Flat Top Billet Steel Piston', true, false),
  ('Flat Top Cast Aluminum Piston', false, true),
  ('Flat Top Cast Iron Piston', false, true),
  ('Flat Top Cast Steel Piston', false, true),
  ('Flat Top Forged Aluminum Piston', true, false),
  ('Flat Top Forged Steel Piston', true, false),
  ('Flat Top Powder Metal Piston', true, false),
  ('Flat Top Titanium Piston', true, false),
  ('Billet Aluminum Four Rotor Rotor Housing', true, false),
  ('Billet Aluminum Single Rotor Rotor Housing', true, false),
  ('Billet Aluminum Three Rotor Rotor Housing', true, false),
  ('Billet Aluminum Twin Rotor Rotor Housing', true, false),
  ('Billet Steel Four Rotor Rotor Housing', true, false),
  ('Billet Steel Single Rotor Rotor Housing', true, false),
  ('Billet Steel Three Rotor Rotor Housing', true, false),
  ('Billet Steel Twin Rotor Rotor Housing', true, false),
  ('Cast Aluminum Four Rotor Rotor Housing', false, true),
  ('Cast Aluminum Single Rotor Rotor Housing', false, true),
  ('Cast Aluminum Three Rotor Rotor Housing', false, true),
  ('Cast Aluminum Twin Rotor Rotor Housing', false, true),
  ('Cast Iron Four Rotor Rotor Housing', false, true),
  ('Cast Iron Single Rotor Rotor Housing', false, true),
  ('Cast Iron Three Rotor Rotor Housing', false, true),
  ('Cast Iron Twin Rotor Rotor Housing', false, true),
  ('Compacted Graphite Iron Four Rotor Rotor Housing', true, false),
  ('Compacted Graphite Iron Single Rotor Rotor Housing', true, false),
  ('Compacted Graphite Iron Three Rotor Rotor Housing', true, false),
  ('Compacted Graphite Iron Twin Rotor Rotor Housing', true, false),
  ('Magnesium Alloy Four Rotor Rotor Housing', true, false),
  ('Magnesium Alloy Single Rotor Rotor Housing', true, false),
  ('Magnesium Alloy Three Rotor Rotor Housing', true, false),
  ('Magnesium Alloy Twin Rotor Rotor Housing', true, false),
  ('Alternator', true, false),
  ('Aluminium', false, true),
  ('Aluminium Powder', false, true),
  ('Apex Seals', true, false),
  ('Base Tire', false, true),
  ('Brake Fluid', true, true),
  ('Brake Lines', false, true),
  ('Brass', false, true),
  ('Bushing Kit', true, false),
  ('Car Battery', true, false),
  ('Carbon Fiber', false, true),
  ('Clutch Kit', true, false),
  ('Coolant', true, true),
  ('Differential Fluid', true, true),
  ('Differential Rebuild Kit', true, false),
  ('Door Assembly', false, true),
  ('Drive Belt', true, false),
  ('Duct Tape', true, true),
  ('Electric Motor', true, false),
  ('Electric Scrap', false, true),
  ('Empty container', false, true),
  ('Engine Oil', true, true),
  ('Engine Swap 1', true, false),
  ('Exhaust Manifold', true, false),
  ('Fuel Filter', true, true),
  ('Fuel Pump', true, false),
  ('Fuel Siphon', true, true),
  ('High Voltage Wiring', true, false),
  ('Iron Powder', false, true),
  ('Jump Starter', false, true),
  ('MAF Sensor', true, false),
  ('Motor Oil (1 Qt)', true, true),
  ('NOS Colour Injector', true, false),
  ('NOS Purge Canister', true, false),
  ('Nos Restrictor Valve', true, false),
  ('O2 Sensor', true, false),
  ('Oil Filter', true, true),
  ('Oil Pump', true, false),
  ('Plastic', false, true),
  ('RI: windows cleaner', true, true),
  ('Radiator', true, false),
  ('Raw Copper', false, true),
  ('Raw Iron', false, true),
  ('Raw Steel', false, true),
  ('Repair Kit', true, true),
  ('Roll Cage', true, false),
  ('Rusty Shovel', true, true),
  ('Scrap Metal', false, true),
  ('Signal Booster', true, false),
  ('Spray', true, false),
  ('Spray Remover', true, true),
  ('Starter Motor', true, false),
  ('Suspension Service Part', true, false),
  ('Suspension Springs', true, false),
  ('Sway Bar', true, false),
  ('Synthetic Acid', false, true),
  ('Thermostat', true, false),
  ('Throttle Position Sensor', true, false),
  ('Timing Belt Kit', true, false),
  ('Timing Chain Kit', true, false),
  ('Timing Gears', true, false),
  ('Torque Converter', true, false),
  ('Tow Rope', false, true),
  ('Transmission Rebuild Kit', true, false),
  ('Vehicle Winch', true, false),
  ('Vehicle alarm level 1', true, false),
  ('Vehicle alarm level 2', true, false),
  ('Vehicle alarm level 3', true, false),
  ('Vehicle alarm level 4', true, false),
  ('Water Pump', true, false),
  ('Windshield', false, true),
  ('boltcutter', true, true),
  ('hammer', true, true),
  ('lithium', false, true),
  ('rubber', false, true),
  ('scissors', true, true),
  ('trowel', true, true),
  ('Off-Road Suspension', true, false),
  ('Race Suspension', true, false),
  ('Sport Suspension', true, false),
  ('Stock Suspension', true, false),
  ('Hydraulic Flat Tappet Set', false, true),
  ('Hydraulic Roller Tappet Set', false, true),
  ('Solid Flat Tappet Set', false, true),
  ('Solid Roller Tappet Set', false, true),
  ('Angle Grinder', true, false),
  ('Compression Tester', true, false),
  ('Electronic Circuit Tester', true, true),
  ('Flashlight', true, true),
  ('Mechanic Bench', false, true),
  ('Mechanic Clipboard', true, false),
  ('Mechanic Toolbox', true, false),
  ('Mechanic Toolkit', true, false),
  ('OBD-II Scanner', true, false),
  ('Tool Box', true, false),
  ('Toolkit', true, true),
  ('Tread Depth Gauge', true, false),
  ('Benefactor 722.6 / NAG1 Transmission (5-speed auto)', true, false),
  ('Benefactor 7G-Drive Transmission (7-speed auto)', true, false),
  ('Built Valve Body', true, false),
  ('Bullworth T-5 Transmission (5-speed manual)', true, false),
  ('Clutch', true, false),
  ('Declasse 3-Speed Transmission (3-speed manual)', true, false),
  ('Declasse 4L80-E Transmission (4-speed auto)', true, false),
  ('Declasse 6L80 Transmission (6-speed auto)', true, false),
  ('Declasse M22 Rock Crusher (4-speed manual)', true, false),
  ('Declasse Powerslide Transmission (2-speed auto)', true, false),
  ('Declasse TH400 Transmission (3-speed auto)', true, false),
  ('Manual Gearbox', true, false),
  ('Pfister 7MT Transmission (7-speed manual)', true, false),
  ('Pneumatic Shifter', true, false),
  ('Race 10-Speed Sequential Transmission (manual)', true, false),
  ('Race 8-Speed Sequential Transmission (manual)', true, false),
  ('Race 9-Speed Sequential Transmission (manual)', true, false),
  ('Tarmac TR-6060 Transmission (6-speed manual)', true, false),
  ('Transmission Fluid (1 Qt)', true, true),
  ('Upgraded Clutch Packs', true, false),
  ('Upgraded Synchronizers', true, false),
  ('Vapid 10R80 Transmission (10-speed auto)', true, false),
  ('Vintage 2-Speed Crash Box (2-speed manual)', true, false),
  ('Zancudo 8HP Transmission (8-speed auto)', true, false),
  ('Zancudo 9HP Transmission (9-speed auto)', true, false),
  ('Beehive Billet Steel Valve Spring Set', false, true),
  ('Beehive Cast Steel Valve Spring Set', false, true),
  ('Beehive Forged Steel Valve Spring Set', false, true),
  ('Beehive Titanium Valve Spring Set', false, true),
  ('Conical Billet Steel Valve Spring Set', false, true),
  ('Conical Cast Steel Valve Spring Set', false, true),
  ('Conical Forged Steel Valve Spring Set', false, true),
  ('Conical Titanium Valve Spring Set', false, true),
  ('Dual Billet Steel Valve Spring Set', false, true),
  ('Dual Cast Steel Valve Spring Set', false, true),
  ('Dual Forged Steel Valve Spring Set', false, true),
  ('Dual Titanium Valve Spring Set', false, true),
  ('Custom Wheel Rims', true, false),
  ('Drag Tire', false, true),
  ('Drift Smoke Tires', true, false),
  ('Drift Tire', false, true),
  ('Off-Road Tire', false, true),
  ('Slick Tires', true, false),
  ('Sport Tire', false, true),
  ('Stock Tire', false, true),
  ('Street Tire', false, true),
  ('Track Tire', false, true)
) as v(name, auto, scrap)
where lower(ci.name) = lower(v.name);

