-- Run this once in the Supabase SQL editor for project ucvsnxexmvxpccyatmmk.
-- Syncs catalogue_items.categories from the updated master CSV (Category +
-- Category 2 columns), so the tile browser on job-items.html/catalogue.html
-- correctly shows each item under every work type it's actually used for --
-- this is what makes the per-component install charge (js/workshop.js's
-- INSTALL_CHARGE_BY_JOB_TYPE -- no schema change needed for that part, it's
-- computed straight from job_items.job_type) actually countable: a
-- mechanic can only add an item under a leg if it's tagged for that leg's
-- category. Customer Price column in the source CSV was ignored per
-- Joanna's note (old data, sql/042 is the live pricing).
--
-- Legacy-flagged items (23) are deactivated, not deleted -- retire-not-delete,
-- same convention as everywhere else in this app.

update catalogue_items ci set categories = v.cats
from (values
  ('Aircraft Engine', '{"Aircraft"}'::text[]),
  ('Aircraft Tire', '{"Aircraft"}'::text[]),
  ('Landing Strut', '{"Aircraft"}'::text[]),
  ('Body Filler', '{"Repair/Service"}'::text[]),
  ('Body Patch', '{"Repair/Service"}'::text[]),
  ('Exterior Cosmetics', '{"Customisation"}'::text[]),
  ('Fiberglass Sheet', '{"Repair/Service"}'::text[]),
  ('Front Fender', '{"Repair/Service","Customisation"}'::text[]),
  ('Hood', '{"Repair/Service","Customisation"}'::text[]),
  ('Rear Fender', '{"Repair/Service","Customisation"}'::text[]),
  ('Trunk Lid', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Exhaust', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Extra Part', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Extras', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Front Bumper', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Grille', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Rear Bumper', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Roof', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Skirts', '{"Repair/Service","Customisation"}'::text[]),
  ('Vehicle Spoiler', '{"Repair/Service","Customisation"}'::text[]),
  ('Brake Rotor', '{"Repair/Service"}'::text[]),
  ('Race Brake Pads', '{"Performance","Repair/Service"}'::text[]),
  ('Sport Brake Pads', '{"Performance","Repair/Service"}'::text[]),
  ('Stock Brake Pads', '{"Performance","Repair/Service"}'::text[]),
  ('Street Brake Pads', '{"Performance","Repair/Service"}'::text[]),
  ('Performance Camshaft', '{"Performance"}'::text[]),
  ('Race Camshaft', '{"Performance"}'::text[]),
  ('Stock/Mild Camshaft', '{"Performance"}'::text[]),
  ('Street Perf Camshaft', '{"Performance"}'::text[]),
  ('Torque/Tow Camshaft', '{"Performance"}'::text[]),
  ('H-Beam Billet Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Billet Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Cast Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Cast Iron Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Cast Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Forged Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Forged Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Powder Metal Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('H-Beam Titanium Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Billet Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Billet Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Cast Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Cast Iron Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Cast Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Forged Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Forged Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Powder Metal Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('I-Beam Titanium Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Billet Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Billet Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Cast Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Cast Iron Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Cast Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Forged Aluminum Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Forged Steel Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Powder Metal Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('X-Beam Titanium Connecting Rod', '{"Engine Manufacture"}'::text[]),
  ('Race Radiator', '{"Performance","Repair/Service"}'::text[]),
  ('Sport Radiator', '{"Performance","Repair/Service"}'::text[]),
  ('Street Radiator', '{"Performance","Repair/Service"}'::text[]),
  ('Billet Crankshaft', '{"Engine Manufacture"}'::text[]),
  ('Cast Crankshaft', '{"Engine Manufacture"}'::text[]),
  ('Forged Crankshaft', '{"Engine Manufacture"}'::text[]),
  ('Factory Cast Aluminum Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Factory Cast Iron Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Factory Cast Steel Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Factory Forged Aluminum Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Factory Forged Steel Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Ported & Polished Cast Aluminum Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Ported & Polished Cast Iron Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Ported & Polished Cast Steel Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Ported & Polished Forged Aluminum Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('Ported & Polished Forged Steel Cylinder Head', '{"Engine Manufacture"}'::text[]),
  ('4WD Conversion Kit', '{"Performance"}'::text[]),
  ('AWD Conversion Kit', '{"Performance"}'::text[]),
  ('Differential Re-Gear Kit', '{"Performance"}'::text[]),
  ('Drivetrain Part', '{"Repair/Service"}'::text[]),
  ('FWD Conversion Kit', '{"Performance"}'::text[]),
  ('RWD Conversion Kit', '{"Performance"}'::text[]),
  ('EV Drive Motor', '{"Repair/Service"}'::text[]),
  ('EV Power Inverter', '{"Repair/Service"}'::text[]),
  ('EV Traction Battery', '{"Repair/Service"}'::text[]),
  ('Air Filter', '{"Repair/Service"}'::text[]),
  ('Copper Standard Spark Plug', '{"Repair/Service","Performance"}'::text[]),
  ('Head Gasket Set', '{"Engine Manufacture","Repair/Service"}'::text[]),
  ('Iridium Spark Plug', '{"Repair/Service","Performance"}'::text[]),
  ('Platinum Spark Plug', '{"Repair/Service","Performance"}'::text[]),
  ('Aluminum-Tin Conrod Bearing', '{"Engine Manufacture"}'::text[]),
  ('Aluminum-Tin Main Bearing', '{"Engine Manufacture"}'::text[]),
  ('Bi-Metal Race Conrod Bearing', '{"Engine Manufacture"}'::text[]),
  ('Bi-Metal Race Main Bearing', '{"Engine Manufacture"}'::text[]),
  ('Tri-Metal Conrod Bearing', '{"Engine Manufacture"}'::text[]),
  ('Tri-Metal Main Bearing', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Flat 2 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Flat 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Flat 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Flat 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Inline 3 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Inline 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Inline 5 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Inline 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Inline 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum L4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Single Piston Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum V-Twin Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum V10 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum V12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum V16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum V4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum V6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum V8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum W12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum W16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum W18 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum W6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum W8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Flat 2 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Flat 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Flat 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Flat 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Inline 3 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Inline 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Inline 5 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Inline 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Inline 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel L4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Single Piston Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel V-Twin Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel V10 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel V12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel V16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel V4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel V6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel V8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel W12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel W16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel W18 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel W6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel W8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Flat 2 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Flat 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Flat 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Flat 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Inline 3 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Inline 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Inline 5 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Inline 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Inline 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum L4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Single Piston Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum V-Twin Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum V10 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum V12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum V16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum V4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum V6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum V8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum W12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum W16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum W18 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum W6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum W8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Flat 2 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Flat 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Flat 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Flat 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Inline 3 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Inline 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Inline 5 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Inline 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Inline 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron L4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Single Piston Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron V-Twin Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron V10 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron V12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron V16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron V4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron V6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron V8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron W12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron W16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron W18 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron W6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron W8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Flat 2 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Flat 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Flat 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Flat 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Inline 3 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Inline 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Inline 5 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Inline 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Inline 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron L4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Single Piston Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron V-Twin Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron V10 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron V12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron V16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron V4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron V6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron V8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron W12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron W16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron W18 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron W6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron W8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Flat 2 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Flat 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Flat 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Flat 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Inline 3 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Inline 4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Inline 5 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Inline 6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Inline 8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy L4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Single Piston Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy V-Twin Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy V10 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy V12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy V16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy V4 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy V6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy V8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy W12 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy W16 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy W18 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy W6 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy W8 Engine Block', '{"Engine Manufacture"}'::text[]),
  ('Anti-Lag System Kit', '{"Performance"}'::text[]),
  ('Boost Controller', '{"Performance"}'::text[]),
  ('Large Centrifugal Supercharger', '{"Performance"}'::text[]),
  ('Large Positive Displacement Supercharger', '{"Performance"}'::text[]),
  ('Medium Centrifugal Supercharger', '{"Performance"}'::text[]),
  ('Medium Positive Displacement Supercharger', '{"Performance"}'::text[]),
  ('Nitrous Bottle (Refill)', '{"Performance"}'::text[]),
  ('Nitrous Kit - 100 Shot', '{"Performance"}'::text[]),
  ('Nitrous Kit - 200 Shot', '{"Performance"}'::text[]),
  ('Nitrous Kit - 300 Shot', '{"Performance"}'::text[]),
  ('Nitrous Kit - 50 Shot', '{"Performance"}'::text[]),
  ('Race Intercooler', '{"Performance"}'::text[]),
  ('Small Centrifugal Supercharger', '{"Performance"}'::text[]),
  ('Small Positive Displacement Supercharger', '{"Performance"}'::text[]),
  ('Stock Intercooler', '{"Performance"}'::text[]),
  ('Street Intercooler', '{"Performance"}'::text[]),
  ('Turbocharger - Large Compressor / Large Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Large Compressor / Medium Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Large Compressor / Small Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Medium Compressor / Large Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Medium Compressor / Medium Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Medium Compressor / Small Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Small Compressor / Large Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Small Compressor / Medium Turbine', '{"Performance"}'::text[]),
  ('Turbocharger - Small Compressor / Small Turbine', '{"Performance"}'::text[]),
  ('Window Part', '{"Repair/Service"}'::text[]),
  ('Window Tint Kit', '{"Customisation"}'::text[]),
  ('glass', '{"Scrap Material"}'::text[]),
  ('Carplay Installer Tool', '{"Customisation"}'::text[]),
  ('Custom Vehicle Horn', '{"Customisation"}'::text[]),
  ('Internal Cosmetics', '{"Customisation"}'::text[]),
  ('Seat Cosmetics', '{"Customisation"}'::text[]),
  ('Subwoofer', '{"Customisation"}'::text[]),
  ('Taillight Assembly', '{"Repair/Service"}'::text[]),
  ('Underglow LEDS', '{"Customisation"}'::text[]),
  ('Xenon Headlights', '{"Customisation"}'::text[]),
  ('Customized Plates', '{"Customisation"}'::text[]),
  ('Decal Remover', '{"Tools"}'::text[]),
  ('Livery Roll', '{"Customisation"}'::text[]),
  ('Vehicle Spray Can', '{"Customisation"}'::text[]),
  ('Vehicle Wax Kit', '{"Tools"}'::text[]),
  ('Cast Iron (Standard) Ring Pack', '{"Engine Manufacture"}'::text[]),
  ('Moly-Coated Race Ring Pack', '{"Engine Manufacture"}'::text[]),
  ('Steel Performance Ring Pack', '{"Engine Manufacture"}'::text[]),
  ('Dished Billet Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Billet Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Cast Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Cast Iron Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Cast Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Forged Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Forged Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Powder Metal Piston', '{"Engine Manufacture"}'::text[]),
  ('Dished Titanium Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Billet Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Billet Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Cast Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Cast Iron Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Cast Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Forged Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Forged Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Powder Metal Piston', '{"Engine Manufacture"}'::text[]),
  ('Domed Titanium Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Billet Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Billet Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Cast Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Cast Iron Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Cast Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Forged Aluminum Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Forged Steel Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Powder Metal Piston', '{"Engine Manufacture"}'::text[]),
  ('Flat Top Titanium Piston', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Four Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Single Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Three Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Billet Aluminum Twin Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Four Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Single Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Three Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Billet Steel Twin Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Four Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Single Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Three Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Aluminum Twin Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Four Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Single Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Three Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Cast Iron Twin Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Four Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Single Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Three Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Compacted Graphite Iron Twin Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Four Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Single Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Three Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Magnesium Alloy Twin Rotor Rotor Housing', '{"Engine Manufacture"}'::text[]),
  ('Alternator', '{"Repair/Service"}'::text[]),
  ('Aluminium', '{"Scrap Material"}'::text[]),
  ('Aluminium Powder', '{"Scrap Material"}'::text[]),
  ('Apex Seals', '{"Engine Manufacture"}'::text[]),
  ('Base Tire', '{"Repair/Service"}'::text[]),
  ('Brake Fluid', '{"Repair/Service"}'::text[]),
  ('Brake Lines', '{"Repair/Service"}'::text[]),
  ('Brass', '{"Scrap Material"}'::text[]),
  ('Bushing Kit', '{"Repair/Service"}'::text[]),
  ('Car Battery', '{"Repair/Service"}'::text[]),
  ('Carbon Fiber', '{"Scrap Material"}'::text[]),
  ('Clutch Kit', '{"Repair/Service"}'::text[]),
  ('Coolant', '{"Repair/Service"}'::text[]),
  ('Differential Fluid', '{"Repair/Service"}'::text[]),
  ('Differential Rebuild Kit', '{"Repair/Service"}'::text[]),
  ('Door Assembly', '{"Repair/Service"}'::text[]),
  ('Drive Belt', '{"Repair/Service"}'::text[]),
  ('Duct Tape', '{"Repair/Service"}'::text[]),
  ('Electric Scrap', '{"Scrap Material"}'::text[]),
  ('Empty container', '{"Scrap Material"}'::text[]),
  ('Exhaust Manifold', '{"Engine Manufacture"}'::text[]),
  ('Fuel Filter', '{"Repair/Service"}'::text[]),
  ('Fuel Pump', '{"Repair/Service"}'::text[]),
  ('Fuel Siphon', '{"Tools"}'::text[]),
  ('High Voltage Wiring', '{"Scrap Material"}'::text[]),
  ('Iron Powder', '{"Scrap Material"}'::text[]),
  ('Jump Starter', '{"Tools"}'::text[]),
  ('MAF Sensor', '{"Repair/Service"}'::text[]),
  ('Motor Oil (1 Qt)', '{"Repair/Service"}'::text[]),
  ('O2 Sensor', '{"Repair/Service"}'::text[]),
  ('Oil Filter', '{"Repair/Service"}'::text[]),
  ('Oil Pump', '{"Repair/Service"}'::text[]),
  ('Plastic', '{"Scrap Material"}'::text[]),
  ('Radiator', '{"Repair/Service"}'::text[]),
  ('Raw Copper', '{"Scrap Material"}'::text[]),
  ('Raw Iron', '{"Scrap Material"}'::text[]),
  ('Raw Steel', '{"Scrap Material"}'::text[]),
  ('Rusty Shovel', '{"Tools"}'::text[]),
  ('Scrap Metal', '{"Scrap Material"}'::text[]),
  ('Signal Booster', '{"Tools"}'::text[]),
  ('Spray', '{"Tools"}'::text[]),
  ('Spray Remover', '{"Tools"}'::text[]),
  ('Starter Motor', '{"Repair/Service"}'::text[]),
  ('Suspension Service Part', '{"Repair/Service"}'::text[]),
  ('Suspension Springs', '{"Repair/Service"}'::text[]),
  ('Sway Bar', '{"Repair/Service"}'::text[]),
  ('Synthetic Acid', '{"Scrap Material"}'::text[]),
  ('Thermostat', '{"Repair/Service"}'::text[]),
  ('Throttle Position Sensor', '{"Repair/Service"}'::text[]),
  ('Timing Belt Kit', '{"Engine Manufacture","Repair/Service"}'::text[]),
  ('Timing Chain Kit', '{"Engine Manufacture","Repair/Service"}'::text[]),
  ('Timing Gears', '{"Engine Manufacture","Repair/Service"}'::text[]),
  ('Torque Converter', '{"Repair/Service"}'::text[]),
  ('Tow Rope', '{"Tools"}'::text[]),
  ('Transmission Rebuild Kit', '{"Repair/Service"}'::text[]),
  ('Vehicle Winch', '{"Tools"}'::text[]),
  ('Vehicle alarm level 1', '{"Customisation"}'::text[]),
  ('Vehicle alarm level 2', '{"Customisation"}'::text[]),
  ('Vehicle alarm level 3', '{"Customisation"}'::text[]),
  ('Vehicle alarm level 4', '{"Customisation"}'::text[]),
  ('Water Pump', '{"Repair/Service"}'::text[]),
  ('Windshield', '{"Repair/Service"}'::text[]),
  ('boltcutter', '{"Tools"}'::text[]),
  ('hammer', '{"Tools"}'::text[]),
  ('lithium', '{"Scrap Material"}'::text[]),
  ('rubber', '{"Scrap Material"}'::text[]),
  ('scissors', '{"Tools"}'::text[]),
  ('trowel', '{"Tools"}'::text[]),
  ('Off-Road Suspension', '{"Performance","Repair/Service"}'::text[]),
  ('Race Suspension', '{"Performance","Repair/Service"}'::text[]),
  ('Sport Suspension', '{"Performance","Repair/Service"}'::text[]),
  ('Stock Suspension', '{"Performance","Repair/Service"}'::text[]),
  ('Hydraulic Flat Tappet Set', '{"Engine Manufacture"}'::text[]),
  ('Hydraulic Roller Tappet Set', '{"Engine Manufacture"}'::text[]),
  ('Solid Flat Tappet Set', '{"Engine Manufacture"}'::text[]),
  ('Solid Roller Tappet Set', '{"Engine Manufacture"}'::text[]),
  ('Angle Grinder', '{"Tools"}'::text[]),
  ('Compression Tester', '{"Tools"}'::text[]),
  ('Electronic Circuit Tester', '{"Tools"}'::text[]),
  ('Flashlight', '{"Tools"}'::text[]),
  ('Mechanic Bench', '{"Tools"}'::text[]),
  ('Mechanic Clipboard', '{"Tools"}'::text[]),
  ('Mechanic Toolbox', '{"Tools"}'::text[]),
  ('Mechanic Toolkit', '{"Tools"}'::text[]),
  ('OBD-II Scanner', '{"Tools"}'::text[]),
  ('Tool Box', '{"Tools"}'::text[]),
  ('Toolkit', '{"Tools"}'::text[]),
  ('Tread Depth Gauge', '{"Tools"}'::text[]),
  ('Benefactor 722.6 / NAG1 Transmission (5-speed auto)', '{"Performance"}'::text[]),
  ('Benefactor 7G-Drive Transmission (7-speed auto)', '{"Performance"}'::text[]),
  ('Built Valve Body', '{"Performance"}'::text[]),
  ('Bullworth T-5 Transmission (5-speed manual)', '{"Performance"}'::text[]),
  ('Declasse 3-Speed Transmission (3-speed manual)', '{"Performance"}'::text[]),
  ('Declasse 4L80-E Transmission (4-speed auto)', '{"Performance"}'::text[]),
  ('Declasse 6L80 Transmission (6-speed auto)', '{"Performance"}'::text[]),
  ('Declasse M22 Rock Crusher (4-speed manual)', '{"Performance"}'::text[]),
  ('Declasse Powerslide Transmission (2-speed auto)', '{"Performance"}'::text[]),
  ('Declasse TH400 Transmission (3-speed auto)', '{"Performance"}'::text[]),
  ('Pfister 7MT Transmission (7-speed manual)', '{"Performance"}'::text[]),
  ('Pneumatic Shifter', '{"Performance"}'::text[]),
  ('Race 10-Speed Sequential Transmission (manual)', '{"Performance"}'::text[]),
  ('Race 8-Speed Sequential Transmission (manual)', '{"Performance"}'::text[]),
  ('Race 9-Speed Sequential Transmission (manual)', '{"Performance"}'::text[]),
  ('Tarmac TR-6060 Transmission (6-speed manual)', '{"Performance"}'::text[]),
  ('Transmission Fluid (1 Qt)', '{"Repair/Service"}'::text[]),
  ('Upgraded Clutch Packs', '{"Performance"}'::text[]),
  ('Upgraded Synchronizers', '{"Performance"}'::text[]),
  ('Vapid 10R80 Transmission (10-speed auto)', '{"Performance"}'::text[]),
  ('Vintage 2-Speed Crash Box (2-speed manual)', '{"Performance"}'::text[]),
  ('Zancudo 8HP Transmission (8-speed auto)', '{"Performance"}'::text[]),
  ('Zancudo 9HP Transmission (9-speed auto)', '{"Performance"}'::text[]),
  ('Beehive Billet Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Beehive Cast Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Beehive Forged Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Beehive Titanium Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Conical Billet Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Conical Cast Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Conical Forged Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Conical Titanium Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Dual Billet Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Dual Cast Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Dual Forged Steel Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Dual Titanium Valve Spring Set', '{"Engine Manufacture"}'::text[]),
  ('Custom Wheel Rims', '{"Customisation"}'::text[]),
  ('Drag Tire', '{"Performance"}'::text[]),
  ('Drift Smoke Tires', '{"Customisation"}'::text[]),
  ('Drift Tire', '{"Performance"}'::text[]),
  ('Off-Road Tire', '{"Performance"}'::text[]),
  ('Sport Tire', '{"Performance"}'::text[]),
  ('Stock Tire', '{"Performance"}'::text[]),
  ('Street Tire', '{"Performance"}'::text[]),
  ('Track Tire', '{"Performance"}'::text[])
) as v(name, cats)
where lower(ci.name) = lower(v.name);

-- 23 Legacy items -- hidden from selection, not deleted.
update catalogue_items set active = false
where lower(name) in (
  'brake pads',
  'brake replacement',
  'brake upgrade',
  'battery coolant',
  'drive train pump',
  'drivetrain fluid',
  'ev battery',
  'spark plugs',
  'nitrous install kit',
  'supercharger turbo',
  'mechanic tablet',
  'electric motor',
  'engine oil',
  'engine swap 1',
  'nos colour injector',
  'nos purge canister',
  'nos restrictor valve',
  'ri: windows cleaner',
  'repair kit',
  'roll cage',
  'clutch',
  'manual gearbox',
  'slick tires'
);
