-- Run this once in the Supabase SQL editor for project ucvsnxexmvxpccyatmmk.
--
-- A third real-money figure per catalogue item, distinct from the two that
-- already exist:
--   purchase_cost  -- what it costs to buy the item off the Autoparts/
--                      Scrapyard store's own shelf ("shop price" in
--                      Joanna's terms). This already IS what recordPurchase()
--                      (js/catalogue.js) asks for/records at purchase time --
--                      no change to its meaning, just clarifying it here.
--   customer_price -- what the mechanic shop bills the customer.
--   import_price   -- NEW. What it costs to run the "import" that stocks
--                      the Autoparts/Scrapyard store's own inventory with
--                      the item in the first place, paid before anyone can
--                      buy it at purchase_cost/"shop price". Nullable --
--                      populated per item once Joanna supplies real figures
--                      (same "To confirm until set" convention as every
--                      other price column, formatMoney() in js/workshop.js).
--
-- No grant/RLS changes needed -- sql/003_grants.sql's table-level grant and
-- sql/025's "using (true)" update policy on catalogue_items already cover
-- any column added to the table, this one included.

alter table catalogue_items add column if not exists import_price numeric(12,2);
