-- Run this once in the Supabase SQL editor for project ucvsnxexmvxpccyatmmk.
--
-- Applies Joanna's reviewed pricing sheet ("PDM Mechanic 4.0 - Sheet7",
-- 461 priced rows) to catalogue_items.customer_price. Only customer_price
-- moves -- the sheet's own Import price column matches what's already live in
-- purchase_cost, so that's left untouched, same for shop_price/export_price.
--
-- Name matching normalizes em-dash/en-dash to a plain hyphen before comparing,
-- same guard as sql/051/053 -- the live catalogue uses a plain hyphen for the
-- "Nitrous Kit - X Shot"/"Turbocharger - X / Y" family (confirmed), some
-- source sheets render those with an em-dash instead.

update catalogue_items ci set
  customer_price = v.new_price
from (values
  ('4WD Conversion Kit', 3420.00),
  ('Air Filter', 43.20),
  ('Aircraft Engine', 21660.00),
  ('Aircraft Tire', 1197.00),
  ('Alternator', 404.00),
  ('Aluminium', 6.00),
  ('Aluminium Powder', 6.00),
  ('Aluminum-Tin Conrod Bearing', 35.64),
  ('Aluminum-Tin Main Bearing', 41.04),
  ('Angle Grinder', 162.00),
  ('Anti-Lag System Kit', 1995.00),
  ('Apex Seals', 153.90),
  ('AWD Conversion Kit', 3135.00),
  ('Base Tire', 125.28),
  ('Beehive Billet Steel Valve Spring Set', 62.64),
  ('Beehive Cast Steel Valve Spring Set', 25.92),
  ('Beehive Forged Steel Valve Spring Set', 35.64),
  ('Beehive Titanium Valve Spring Set', 114.48),
  ('Benefactor 722.6 / NAG1 Transmission (5-speed auto)', 1710.00),
  ('Benefactor 7G-Drive Transmission (7-speed auto)', 2508.00),
  ('Bi-Metal Race Conrod Bearing', 77.76),
  ('Bi-Metal Race Main Bearing', 88.56),
  ('Billet Aluminum Flat 2 Engine Block', 1339.20),
  ('Billet Aluminum Flat 4 Engine Block', 1909.20),
  ('Billet Aluminum Flat 6 Engine Block', 2508.00),
  ('Billet Aluminum Flat 8 Engine Block', 3106.20),
  ('Billet Aluminum Four Rotor Rotor Housing', 5928.00),
  ('Billet Aluminum Inline 3 Engine Block', 1425.00),
  ('Billet Aluminum Inline 4 Engine Block', 1653.00),
  ('Billet Aluminum Inline 5 Engine Block', 1938.00),
  ('Billet Aluminum Inline 6 Engine Block', 2166.00),
  ('Billet Aluminum Inline 8 Engine Block', 2679.00),
  ('Billet Aluminum L4 Engine Block', 1653.00),
  ('Billet Aluminum Single Piston Engine Block', 1064.00),
  ('Billet Aluminum Single Rotor Rotor Housing', 2451.00),
  ('Billet Aluminum Three Rotor Rotor Housing', 4731.00),
  ('Billet Aluminum Twin Rotor Rotor Housing', 3591.00),
  ('Billet Aluminum V-Twin Engine Block', 1282.20),
  ('Billet Aluminum V10 Engine Block', 3534.00),
  ('Billet Aluminum V12 Engine Block', 4104.00),
  ('Billet Aluminum V16 Engine Block', 5215.20),
  ('Billet Aluminum V4 Engine Block', 1824.00),
  ('Billet Aluminum V6 Engine Block', 2394.00),
  ('Billet Aluminum V8 Engine Block', 2964.00),
  ('Billet Aluminum W12 Engine Block', 5016.00),
  ('Billet Aluminum W16 Engine Block', 6384.00),
  ('Billet Aluminum W18 Engine Block', 7125.00),
  ('Billet Aluminum W6 Engine Block', 2935.20),
  ('Billet Aluminum W8 Engine Block', 3648.00),
  ('Billet Crankshaft', 2565.00),
  ('Billet Steel Flat 2 Engine Block', 864.50),
  ('Billet Steel Flat 4 Engine Block', 1229.90),
  ('Billet Steel Flat 6 Engine Block', 1396.20),
  ('Billet Steel Flat 8 Engine Block', 1710.00),
  ('Billet Steel Four Rotor Rotor Housing', 3277.20),
  ('Billet Steel Inline 3 Engine Block', 931.00),
  ('Billet Steel Inline 4 Engine Block', 1064.00),
  ('Billet Steel Inline 5 Engine Block', 1263.50),
  ('Billet Steel Inline 6 Engine Block', 1396.50),
  ('Billet Steel Inline 8 Engine Block', 1482.00),
  ('Billet Steel L4 Engine Block', 1064.00),
  ('Billet Steel Single Piston Engine Block', 668.80),
  ('Billet Steel Single Rotor Rotor Housing', 1368.00),
  ('Billet Steel Three Rotor Rotor Housing', 2622.00),
  ('Billet Steel Twin Rotor Rotor Housing', 1995.00),
  ('Billet Steel V-Twin Engine Block', 830.90),
  ('Billet Steel V10 Engine Block', 1966.20),
  ('Billet Steel V12 Engine Block', 2280.00),
  ('Billet Steel V16 Engine Block', 2907.00),
  ('Billet Steel V4 Engine Block', 1197.00),
  ('Billet Steel V6 Engine Block', 1339.20),
  ('Billet Steel V8 Engine Block', 1653.00),
  ('Billet Steel W10 Engine Block', 10.00),
  ('Billet Steel W12 Engine Block', 2793.00),
  ('Billet Steel W16 Engine Block', 3562.20),
  ('Billet Steel W18 Engine Block', 3933.00),
  ('Billet Steel W6 Engine Block', 1624.20),
  ('Billet Steel W8 Engine Block', 2023.20),
  ('Body Filler', 41.04),
  ('Body Patch', 88.56),
  ('boltcutter', 66.60),
  ('Boost Controller', 721.60),
  ('Brake Fluid', 27.90),
  ('Brake Lines', 167.04),
  ('Brake Rotor', 241.92),
  ('Brass', 8.40),
  ('Built Valve Body', 1596.00),
  ('Bullworth T-5 Transmission (5-speed manual)', 1596.00),
  ('Bushing Kit', 167.20),
  ('Car Battery', 265.60),
  ('Carbon Fiber', 69.12),
  ('Carplay Installer Tool', 830.90),
  ('Cast Aluminum Flat 2 Engine Block', 670.08),
  ('Cast Aluminum Flat 4 Engine Block', 855.12),
  ('Cast Aluminum Flat 6 Engine Block', 1099.56),
  ('Cast Aluminum Flat 8 Engine Block', 1385.16),
  ('Cast Aluminum Four Rotor Rotor Housing', 2234.88),
  ('Cast Aluminum Inline 3 Engine Block', 716.16),
  ('Cast Aluminum Inline 4 Engine Block', 740.88),
  ('Cast Aluminum Inline 5 Engine Block', 855.12),
  ('Cast Aluminum Inline 6 Engine Block', 977.76),
  ('Cast Aluminum Inline 8 Engine Block', 1181.04),
  ('Cast Aluminum L4 Engine Block', 740.88),
  ('Cast Aluminum Single Piston Engine Block', 456.00),
  ('Cast Aluminum Single Rotor Rotor Housing', 1099.56),
  ('Cast Aluminum Three Rotor Rotor Housing', 1815.84),
  ('Cast Aluminum Twin Rotor Rotor Housing', 1361.52),
  ('Cast Aluminum V-Twin Engine Block', 642.24),
  ('Cast Aluminum V12 Engine Block', 1571.04),
  ('Cast Aluminum V16 Engine Block', 1990.08),
  ('Cast Aluminum V4 Engine Block', 814.80),
  ('Cast Aluminum V6 Engine Block', 1059.24),
  ('Cast Aluminum V8 Engine Block', 1303.68),
  ('Cast Aluminum V10 Engine Block', 1326.96),
  ('Cast Aluminum W12 Engine Block', 1920.24),
  ('Cast Aluminum W16 Engine Block', 2444.40),
  ('Cast Aluminum W18 Engine Block', 2688.48),
  ('Cast Aluminum W6 Engine Block', 2688.48),
  ('Cast Aluminum W8 Engine Block', 1396.80),
  ('Cast Crankshaft', 418.56),
  ('Cast Iron (Standard) Ring Pack', 1303.68),
  ('Cast Iron Flat 2 Engine Block', 483.84),
  ('Cast Iron Flat 4 Engine Block', 697.92),
  ('Cast Iron Flat 6 Engine Block', 798.00),
  ('Cast Iron Flat 8 Engine Block', 977.76),
  ('Cast Iron Four Rotor Rotor Housing', 1606.32),
  ('Cast Iron Inline 3 Engine Block', 511.68),
  ('Cast Iron Inline 4 Engine Block', 604.80),
  ('Cast Iron Inline 5 Engine Block', 697.92),
  ('Cast Iron Inline 6 Engine Block', 791.04),
  ('Cast Iron Inline 8 Engine Block', 855.12),
  ('Cast Iron L4 Engine Block', 604.80),
  ('Cast Iron Single Piston Engine Block', 325.44),
  ('Cast Iron Single Rotor Rotor Housing', 773.64),
  ('Cast Iron Three Rotor Rotor Housing', 1291.68),
  ('Cast Iron Twin Rotor Rotor Housing', 1140.72),
  ('Cast Iron V-Twin Engine Block', 465.60),
  ('Cast Iron V10 Engine Block', 1140.72),
  ('Cast Iron V12 Engine Block', 1303.68),
  ('Cast Iron V16 Engine Block', 1431.36),
  ('Cast Iron V4 Engine Block', 670.08),
  ('Cast Iron V6 Engine Block', 765.24),
  ('Cast Iron V8 Engine Block', 936.60),
  ('Cast Iron W12 Engine Block', 1361.52),
  ('Cast Iron W16 Engine Block', 1746.00),
  ('Cast Iron W18 Engine Block', 1920.24),
  ('Cast Iron W6 Engine Block', 936.60),
  ('Cast Iron W8 Engine Block', 1140.72),
  ('Clutch Kit', 1263.50),
  ('Compacted Graphite Iron Flat 2 Engine Block', 691.20),
  ('Compacted Graphite Iron Flat 4 Engine Block', 864.50),
  ('Compacted Graphite Iron Flat 6 Engine Block', 1130.50),
  ('Compacted Graphite Iron Flat 8 Engine Block', 1396.50),
  ('Compacted Graphite Iron Four Rotor Rotor Housing', 2280.00),
  ('Compacted Graphite Iron Inline 3 Engine Block', 729.60),
  ('Compacted Graphite Iron Inline 4 Engine Block', 764.40),
  ('Compacted Graphite Iron Inline 5 Engine Block', 864.50),
  ('Compacted Graphite Iron Inline 6 Engine Block', 997.50),
  ('Compacted Graphite Iron Inline 8 Engine Block', 1229.90),
  ('Compacted Graphite Iron L4 Engine Block', 764.40),
  ('Compacted Graphite Iron Single Piston Engine Block', 463.20),
  ('Compacted Graphite Iron Single Rotor Rotor Housing', 1096.90),
  ('Compacted Graphite Iron Three Rotor Rotor Housing', 1852.20),
  ('Compacted Graphite Iron Twin Rotor Rotor Housing', 1396.20),
  ('Compacted Graphite Iron V-Twin Engine Block', 660.80),
  ('Compacted Graphite Iron V10 Engine Block', 1368.00),
  ('Compacted Graphite Iron V12 Engine Block', 1596.00),
  ('Compacted Graphite Iron V16 Engine Block', 2023.20),
  ('Compacted Graphite Iron V4 Engine Block', 830.90),
  ('Compacted Graphite Iron V6 Engine Block', 1096.90),
  ('Compacted Graphite Iron V8 Engine Block', 1330.00),
  ('Compacted Graphite Iron W12 Engine Block', 1966.20),
  ('Compacted Graphite Iron W16 Engine Block', 2479.20),
  ('Compacted Graphite Iron W18 Engine Block', 2764.20),
  ('Compacted Graphite Iron W6 Engine Block', 1330.00),
  ('Compacted Graphite Iron W8 Engine Block', 1425.00),
  ('Compression Tester', 288.80),
  ('Conical Billet Steel Valve Spring Set', 51.84),
  ('Conical Cast Steel Valve Spring Set', 20.52),
  ('Conical Forged Steel Valve Spring Set', 31.32),
  ('Conical Titanium Valve Spring Set', 93.96),
  ('Coolant', 53.10),
  ('Copper Standard Spark Plug', 20.52),
  ('Custom Vehicle Horn', 20.70),
  ('Custom Wheel Rims', 106.20),
  ('Customized Plates', 82.80),
  ('Decal Remover', 63.90),
  ('Declasse 3-Speed Transmission (3-speed manual)', 1130.50),
  ('Declasse 4L80-E Transmission (4-speed auto)', 1482.00),
  ('Declasse 6L80 Transmission (6-speed auto)', 1995.00),
  ('Declasse Hydro-Drive 400 (3-speed auto)', 10.00),
  ('Declasse M22 Rock Crusher (4-speed manual)', 1368.00),
  ('Declasse Powerslide Transmission (2-speed auto)', 1197.00),
  ('Declasse TH400 Transmission (3-speed auto)', 1330.00),
  ('Differential Fluid', 25.20),
  ('Differential Re-Gear Kit', 864.50),
  ('Differential Rebuild Kit', 997.50),
  ('Dished Billet Aluminum Piston', 334.40),
  ('Dished Billet Steel Piston', 273.60),
  ('Dished Cast Aluminum Piston', 125.28),
  ('Dished Cast Iron Piston', 77.76),
  ('Dished Cast Steel Piston', 104.76),
  ('Dished Forged Aluminum Piston', 204.80),
  ('Dished Forged Steel Piston', 162.00),
  ('Dished Powder Metal Piston', 136.80),
  ('Dished Titanium Piston', 638.40),
  ('Domed Billet Aluminum Piston', 349.60),
  ('Domed Billet Steel Piston', 280.80),
  ('Domed Cast Aluminum Piston', 125.28),
  ('Domed Cast Iron Piston', 77.76),
  ('Domed Cast Steel Piston', 104.76),
  ('Domed Forged Aluminum Piston', 220.00),
  ('Domed Forged Steel Piston', 171.00),
  ('Domed Powder Metal Piston', 136.80),
  ('Domed Titanium Piston', 668.80),
  ('Door Assembly', 18.00),
  ('Drag Tire', 733.32),
  ('Drift Smoke Tires', 737.60),
  ('Drift Tire', 558.72),
  ('Drive Belt', 155.70),
  ('Drivetrain Part', 493.60),
  ('Dual Billet Steel Valve Spring Set', 77.76),
  ('Dual Cast Steel Valve Spring Set', 31.32),
  ('Dual Forged Steel Valve Spring Set', 41.04),
  ('Dual Titanium Valve Spring Set', 145.80),
  ('Duct Tape', 14.00),
  ('Electric Scrap', 6.00),
  ('Electronic Circuit Tester', 66.60),
  ('Empty container', 10.80),
  ('Engine', 10.00),
  ('EV Drive Motor', 7695.00),
  ('EV Power Inverter', 2394.00),
  ('EV Traction Battery', 3847.20),
  ('Exhaust Manifold', 798.00),
  ('Exterior Cosmetics', 63.90),
  ('Factory Cast Aluminum Cylinder Head', 651.84),
  ('Factory Cast Iron Cylinder Head', 465.60),
  ('Factory Cast Steel Cylinder Head', 558.72),
  ('Factory Forged Aluminum Cylinder Head', 1197.00),
  ('Factory Forged Steel Cylinder Head', 731.50),
  ('Fiberglass Sheet', 167.40),
  ('Flashlight', 42.30),
  ('Flat Top Billet Aluminum Piston', 319.20),
  ('Flat Top Billet Steel Piston', 258.40),
  ('Flat Top Cast Aluminum Piston', 114.48),
  ('Flat Top Cast Iron Piston', 72.36),
  ('Flat Top Cast Steel Piston', 99.36),
  ('Flat Top Forged Aluminum Piston', 197.60),
  ('Flat Top Forged Steel Piston', 153.90),
  ('Flat Top Powder Metal Piston', 127.80),
  ('Flat Top Titanium Piston', 608.00),
  ('Forged Crankshaft', 798.00),
  ('Front Fender', 34.20),
  ('Fuel Filter', 27.00),
  ('Fuel Pump', 245.60),
  ('Fuel Siphon', 162.00),
  ('FWD Conversion Kit', 1710.00),
  ('glass', 15.60),
  ('H-Beam Billet Aluminum Connecting Rod', 349.60),
  ('H-Beam Billet Steel Connecting Rod', 280.80),
  ('H-Beam Cast Aluminum Connecting Rod', 114.48),
  ('H-Beam Cast Iron Connecting Rod', 72.36),
  ('H-Beam Cast Steel Connecting Rod', 104.76),
  ('H-Beam Forged Aluminum Connecting Rod', 197.60),
  ('H-Beam Forged Steel Connecting Rod', 162.00),
  ('H-Beam Powder Metal Connecting Rod', 127.80),
  ('H-Beam Titanium Connecting Rod', 653.60),
  ('hammer', 17.00),
  ('Head Gasket Set', 127.80),
  ('High Voltage Wiring', 166.40),
  ('Hood', 353.28),
  ('Hydraulic Flat Tappet Set', 25.92),
  ('Hydraulic Roller Tappet Set', 41.04),
  ('I-Beam Billet Aluminum Connecting Rod', 304.00),
  ('I-Beam Billet Steel Connecting Rod', 243.20),
  ('I-Beam Cast Aluminum Connecting Rod', 99.36),
  ('I-Beam Cast Iron Connecting Rod', 62.64),
  ('I-Beam Cast Steel Connecting Rod', 88.56),
  ('I-Beam Forged Aluminum Connecting Rod', 174.40),
  ('I-Beam Forged Steel Connecting Rod', 136.80),
  ('I-Beam Powder Metal Connecting Rod', 110.70),
  ('I-Beam Titanium Connecting Rod', 569.60),
  ('Internal Cosmetics', 42.30),
  ('Iridium Spark Plug', 62.64),
  ('Iron Powder', 6.00),
  ('Jump Starter', 214.08),
  ('Landing Strut', 3705.00),
  ('Large Centrifugal Supercharger', 3078.00),
  ('Large Positive Displacement Supercharger', 3876.00),
  ('lithium', 782.04),
  ('Livery Roll', 63.90),
  ('MAF Sensor', 162.00),
  ('Magnesium Alloy Flat 2 Engine Block', 1482.00),
  ('Magnesium Alloy Flat 4 Engine Block', 2137.20),
  ('Magnesium Alloy Flat 6 Engine Block', 2793.00),
  ('Magnesium Alloy Flat 8 Engine Block', 3448.20),
  ('Magnesium Alloy Four Rotor Rotor Housing', 6555.00),
  ('Magnesium Alloy Inline 3 Engine Block', 1567.20),
  ('Magnesium Alloy Inline 4 Engine Block', 1852.20),
  ('Magnesium Alloy Inline 5 Engine Block', 2137.20),
  ('Magnesium Alloy Inline 6 Engine Block', 2422.20),
  ('Magnesium Alloy Inline 8 Engine Block', 2992.20),
  ('Magnesium Alloy L4 Engine Block', 1852.20),
  ('Magnesium Alloy Single Piston Engine Block', 1163.40),
  ('Magnesium Alloy Single Rotor Rotor Housing', 2707.20),
  ('Magnesium Alloy Three Rotor Rotor Housing', 5272.20),
  ('Magnesium Alloy Twin Rotor Rotor Housing', 3990.00),
  ('Magnesium Alloy V-Twin Engine Block', 1425.00),
  ('Magnesium Alloy V10 Engine Block', 3933.00),
  ('Magnesium Alloy V12 Engine Block', 4560.00),
  ('Magnesium Alloy V16 Engine Block', 5814.00),
  ('Magnesium Alloy V4 Engine Block', 2052.00),
  ('Magnesium Alloy V6 Engine Block', 2679.00),
  ('Magnesium Alloy V8 Engine Block', 3306.00),
  ('Magnesium Alloy W12 Engine Block', 5586.00),
  ('Magnesium Alloy W16 Engine Block', 7125.00),
  ('Magnesium Alloy W18 Engine Block', 7866.00),
  ('Magnesium Alloy W6 Engine Block', 3277.20),
  ('Magnesium Alloy W8 Engine Block', 4047.00),
  ('Mechanic Bench', 8205.84),
  ('Mechanic Clipboard', 29.70),
  ('Mechanic Toolbox', 332.80),
  ('Mechanic Toolkit', 334.40),
  ('Medium Centrifugal Supercharger', 2052.00),
  ('Medium Positive Displacement Supercharger', 2565.00),
  ('Moly-Coated Race Ring Pack', 167.40),
  ('Motor Oil (1 Qt)', 27.90),
  ('Nitrous Bottle (Refill)', 493.60),
  ('Nitrous Kit â€” 100 Shot', 2137.20),
  ('Nitrous Kit â€” 200 Shot', 3135.00),
  ('Nitrous Kit â€” 300 Shot', 4560.00),
  ('Nitrous Kit â€” 50 Shot', 1425.00),
  ('O2 Sensor', 119.70),
  ('OBD-II Scanner', 493.60),
  ('Off-Road Suspension', 684.00),
  ('Off-Road Tire', 465.60),
  ('Oil Filter', 46.80),
  ('Oil Pump', 288.80),
  ('Performance Camshaft', 417.60),
  ('Pfister 7MT Transmission (7-speed manual)', 2964.00),
  ('Plastic', 6.00),
  ('Platinum Spark Plug', 35.64),
  ('Pneumatic Shifter', 1824.00),
  ('Ported & Polished Cast Aluminum Cylinder Head', 731.50),
  ('Ported & Polished Cast Iron Cylinder Head', 608.00),
  ('Ported & Polished Cast Steel Cylinder Head', 729.60),
  ('Ported & Polished Forged Aluminum Cylinder Head', 1653.00),
  ('Ported & Polished Forged Steel Cylinder Head', 1163.40),
  ('Race 10-Speed Sequential Transmission (manual)', 6270.00),
  ('Race 8-Speed Sequential Transmission (manual)', 4560.00),
  ('Race 9-Speed Sequential Transmission (manual)', 5415.00),
  ('Race Brake Pads', 1815.60),
  ('Race Camshaft', 1064.00),
  ('Race Intercooler', 1596.00),
  ('Race Radiator', 1368.00),
  ('Race Suspension', 997.50),
  ('Radiator', 364.80),
  ('Raw Copper', 10.80),
  ('Raw Iron', 96.12),
  ('Raw Steel', 19.44),
  ('Rear Fender', 39.60),
  ('rubber', 13.20),
  ('Rusty Shovel', 34.20),
  ('RWD Conversion Kit', 1710.00),
  ('scissors', 11.00),
  ('Scrap Metal', 9.60),
  ('Seat Cosmetics', 167.20),
  ('Signal Booster', 5130.00),
  ('Small Centrifugal Supercharger', 1254.00),
  ('Small Positive Displacement Supercharger', 1596.00),
  ('Solid Flat Tappet Set', 20.52),
  ('Solid Roller Tappet Set', 51.84),
  ('Sport Brake Pads', 1058.40),
  ('Sport Radiator', 997.50),
  ('Sport Suspension', 569.60),
  ('Sport Tire', 418.56),
  ('Spray', 20.70),
  ('Spray Remover', 11.00),
  ('Starter Motor', 319.20),
  ('Steel Performance Ring Pack', 51.84),
  ('Sticky Tape', 0.00),
  ('Stock Brake Pads', 279.36),
  ('Stock Intercooler', 456.00),
  ('Stock Suspension', 228.00),
  ('Stock Tire', 156.60),
  ('Stock/Mild Camshaft', 127.80),
  ('Street Brake Pads', 604.80),
  ('Street Intercooler', 931.00),
  ('Street Perf Camshaft', 288.80),
  ('Street Radiator', 684.00),
  ('Street Tire', 232.32),
  ('Subwoofer', 341.60),
  ('Suspension Service Part', 304.00),
  ('Suspension Springs', 341.60),
  ('Sway Bar', 364.80),
  ('Synthetic Acid', 88.56),
  ('Taillight Assembly', 57.60),
  ('Tarmac TR-6060 Transmission (6-speed manual)', 2052.00),
  ('Thermostat', 81.00),
  ('Throttle Position Sensor', 102.60),
  ('Timing Belt Kit', 136.80),
  ('Timing Chain Kit', 182.40),
  ('Timing Gears', 319.20),
  ('Tool Box', 335.20),
  ('Toolkit', 36.90),
  ('Torque Converter', 1064.00),
  ('Torque/Tow Camshaft', 243.20),
  ('Tow Rope', 51.84),
  ('Track Tire', 744.96),
  ('Transmission Fluid (1 Qt)', 29.70),
  ('Transmission Rebuild Kit', 1368.00),
  ('Tread Depth Gauge', 37.80),
  ('Tri-Metal Conrod Bearing', 20.52),
  ('Tri-Metal Main Bearing', 25.92),
  ('trowel', 13.00),
  ('Trunk Lid', 39.60),
  ('Turbocharger â€” Large Compressor / Large Turbine', 2679.00),
  ('Turbocharger â€” Large Compressor / Medium Turbine', 2479.20),
  ('Turbocharger â€” Large Compressor / Small Turbine', 2280.00),
  ('Turbocharger â€” Medium Compressor / Large Turbine', 1881.00),
  ('Turbocharger â€” Medium Compressor / Medium Turbine', 1681.20),
  ('Turbocharger â€” Medium Compressor / Small Turbine', 1482.00),
  ('Turbocharger â€” Small Compressor / Large Turbine', 1254.00),
  ('Turbocharger â€” Small Compressor / Medium Turbine', 1229.90),
  ('Turbocharger â€” Small Compressor / Small Turbine', 997.50),
  ('Underglow LEDS', 189.60),
  ('Upgraded Clutch Packs', 731.50),
  ('Upgraded Synchronizers', 684.00),
  ('Vapid 10R80 Transmission (10-speed auto)', 3534.00),
  ('Vehicle alarm level 1', 830.90),
  ('Vehicle alarm level 2', 4560.00),
  ('Vehicle alarm level 3', 8550.00),
  ('Vehicle alarm level 4', 11400.00),
  ('Vehicle Exhaust', 110.70),
  ('Vehicle Extra Part', 752.00),
  ('Vehicle Front Bumper', 157.50),
  ('Vehicle Grille', 115.20),
  ('Vehicle Rear Bumper', 171.00),
  ('Vehicle Roof', 123.30),
  ('Vehicle Skirts', 85.50),
  ('Vehicle Spoiler', 85.50),
  ('Vehicle Spray Can', 60.30),
  ('Vehicle Wax Kit', 4.00),
  ('Vehicle Winch', 304.00),
  ('Vintage 2-Speed Crash Box (2-speed manual)', 997.50),
  ('Water Pump', 235.20),
  ('Window Part', 93.96),
  ('Window Tint Kit', 117.90),
  ('Windshield', 241.92),
  ('X-Beam Billet Aluminum Connecting Rod', 395.20),
  ('X-Beam Billet Steel Connecting Rod', 319.20),
  ('X-Beam Cast Aluminum Connecting Rod', 125.28),
  ('X-Beam Cast Iron Connecting Rod', 83.16),
  ('X-Beam Cast Steel Connecting Rod', 114.48),
  ('X-Beam Forged Aluminum Connecting Rod', 228.00),
  ('X-Beam Forged Steel Connecting Rod', 179.10),
  ('X-Beam Powder Metal Connecting Rod', 144.90),
  ('X-Beam Titanium Connecting Rod', 744.80),
  ('Xenon Headlights', 269.76),
  ('Zancudo 8HP Transmission (8-speed auto)', 2850.00),
  ('Zancudo 9HP Transmission (9-speed auto)', 3192.00)
) as v(name, new_price)
where replace(replace(lower(ci.name), chr(8211), '-'), chr(8212), '-')
    = replace(replace(lower(v.name), chr(8211), '-'), chr(8212), '-');

-- Run this afterward to see which of the 461 names above found no match
-- in the live catalogue -- send me the list and I'll reconcile it.
with input(name) as (values
  ('4WD Conversion Kit'),
  ('Air Filter'),
  ('Aircraft Engine'),
  ('Aircraft Tire'),
  ('Alternator'),
  ('Aluminium'),
  ('Aluminium Powder'),
  ('Aluminum-Tin Conrod Bearing'),
  ('Aluminum-Tin Main Bearing'),
  ('Angle Grinder'),
  ('Anti-Lag System Kit'),
  ('Apex Seals'),
  ('AWD Conversion Kit'),
  ('Base Tire'),
  ('Beehive Billet Steel Valve Spring Set'),
  ('Beehive Cast Steel Valve Spring Set'),
  ('Beehive Forged Steel Valve Spring Set'),
  ('Beehive Titanium Valve Spring Set'),
  ('Benefactor 722.6 / NAG1 Transmission (5-speed auto)'),
  ('Benefactor 7G-Drive Transmission (7-speed auto)'),
  ('Bi-Metal Race Conrod Bearing'),
  ('Bi-Metal Race Main Bearing'),
  ('Billet Aluminum Flat 2 Engine Block'),
  ('Billet Aluminum Flat 4 Engine Block'),
  ('Billet Aluminum Flat 6 Engine Block'),
  ('Billet Aluminum Flat 8 Engine Block'),
  ('Billet Aluminum Four Rotor Rotor Housing'),
  ('Billet Aluminum Inline 3 Engine Block'),
  ('Billet Aluminum Inline 4 Engine Block'),
  ('Billet Aluminum Inline 5 Engine Block'),
  ('Billet Aluminum Inline 6 Engine Block'),
  ('Billet Aluminum Inline 8 Engine Block'),
  ('Billet Aluminum L4 Engine Block'),
  ('Billet Aluminum Single Piston Engine Block'),
  ('Billet Aluminum Single Rotor Rotor Housing'),
  ('Billet Aluminum Three Rotor Rotor Housing'),
  ('Billet Aluminum Twin Rotor Rotor Housing'),
  ('Billet Aluminum V-Twin Engine Block'),
  ('Billet Aluminum V10 Engine Block'),
  ('Billet Aluminum V12 Engine Block'),
  ('Billet Aluminum V16 Engine Block'),
  ('Billet Aluminum V4 Engine Block'),
  ('Billet Aluminum V6 Engine Block'),
  ('Billet Aluminum V8 Engine Block'),
  ('Billet Aluminum W12 Engine Block'),
  ('Billet Aluminum W16 Engine Block'),
  ('Billet Aluminum W18 Engine Block'),
  ('Billet Aluminum W6 Engine Block'),
  ('Billet Aluminum W8 Engine Block'),
  ('Billet Crankshaft'),
  ('Billet Steel Flat 2 Engine Block'),
  ('Billet Steel Flat 4 Engine Block'),
  ('Billet Steel Flat 6 Engine Block'),
  ('Billet Steel Flat 8 Engine Block'),
  ('Billet Steel Four Rotor Rotor Housing'),
  ('Billet Steel Inline 3 Engine Block'),
  ('Billet Steel Inline 4 Engine Block'),
  ('Billet Steel Inline 5 Engine Block'),
  ('Billet Steel Inline 6 Engine Block'),
  ('Billet Steel Inline 8 Engine Block'),
  ('Billet Steel L4 Engine Block'),
  ('Billet Steel Single Piston Engine Block'),
  ('Billet Steel Single Rotor Rotor Housing'),
  ('Billet Steel Three Rotor Rotor Housing'),
  ('Billet Steel Twin Rotor Rotor Housing'),
  ('Billet Steel V-Twin Engine Block'),
  ('Billet Steel V10 Engine Block'),
  ('Billet Steel V12 Engine Block'),
  ('Billet Steel V16 Engine Block'),
  ('Billet Steel V4 Engine Block'),
  ('Billet Steel V6 Engine Block'),
  ('Billet Steel V8 Engine Block'),
  ('Billet Steel W10 Engine Block'),
  ('Billet Steel W12 Engine Block'),
  ('Billet Steel W16 Engine Block'),
  ('Billet Steel W18 Engine Block'),
  ('Billet Steel W6 Engine Block'),
  ('Billet Steel W8 Engine Block'),
  ('Body Filler'),
  ('Body Patch'),
  ('boltcutter'),
  ('Boost Controller'),
  ('Brake Fluid'),
  ('Brake Lines'),
  ('Brake Rotor'),
  ('Brass'),
  ('Built Valve Body'),
  ('Bullworth T-5 Transmission (5-speed manual)'),
  ('Bushing Kit'),
  ('Car Battery'),
  ('Carbon Fiber'),
  ('Carplay Installer Tool'),
  ('Cast Aluminum Flat 2 Engine Block'),
  ('Cast Aluminum Flat 4 Engine Block'),
  ('Cast Aluminum Flat 6 Engine Block'),
  ('Cast Aluminum Flat 8 Engine Block'),
  ('Cast Aluminum Four Rotor Rotor Housing'),
  ('Cast Aluminum Inline 3 Engine Block'),
  ('Cast Aluminum Inline 4 Engine Block'),
  ('Cast Aluminum Inline 5 Engine Block'),
  ('Cast Aluminum Inline 6 Engine Block'),
  ('Cast Aluminum Inline 8 Engine Block'),
  ('Cast Aluminum L4 Engine Block'),
  ('Cast Aluminum Single Piston Engine Block'),
  ('Cast Aluminum Single Rotor Rotor Housing'),
  ('Cast Aluminum Three Rotor Rotor Housing'),
  ('Cast Aluminum Twin Rotor Rotor Housing'),
  ('Cast Aluminum V-Twin Engine Block'),
  ('Cast Aluminum V12 Engine Block'),
  ('Cast Aluminum V16 Engine Block'),
  ('Cast Aluminum V4 Engine Block'),
  ('Cast Aluminum V6 Engine Block'),
  ('Cast Aluminum V8 Engine Block'),
  ('Cast Aluminum V10 Engine Block'),
  ('Cast Aluminum W12 Engine Block'),
  ('Cast Aluminum W16 Engine Block'),
  ('Cast Aluminum W18 Engine Block'),
  ('Cast Aluminum W6 Engine Block'),
  ('Cast Aluminum W8 Engine Block'),
  ('Cast Crankshaft'),
  ('Cast Iron (Standard) Ring Pack'),
  ('Cast Iron Flat 2 Engine Block'),
  ('Cast Iron Flat 4 Engine Block'),
  ('Cast Iron Flat 6 Engine Block'),
  ('Cast Iron Flat 8 Engine Block'),
  ('Cast Iron Four Rotor Rotor Housing'),
  ('Cast Iron Inline 3 Engine Block'),
  ('Cast Iron Inline 4 Engine Block'),
  ('Cast Iron Inline 5 Engine Block'),
  ('Cast Iron Inline 6 Engine Block'),
  ('Cast Iron Inline 8 Engine Block'),
  ('Cast Iron L4 Engine Block'),
  ('Cast Iron Single Piston Engine Block'),
  ('Cast Iron Single Rotor Rotor Housing'),
  ('Cast Iron Three Rotor Rotor Housing'),
  ('Cast Iron Twin Rotor Rotor Housing'),
  ('Cast Iron V-Twin Engine Block'),
  ('Cast Iron V10 Engine Block'),
  ('Cast Iron V12 Engine Block'),
  ('Cast Iron V16 Engine Block'),
  ('Cast Iron V4 Engine Block'),
  ('Cast Iron V6 Engine Block'),
  ('Cast Iron V8 Engine Block'),
  ('Cast Iron W12 Engine Block'),
  ('Cast Iron W16 Engine Block'),
  ('Cast Iron W18 Engine Block'),
  ('Cast Iron W6 Engine Block'),
  ('Cast Iron W8 Engine Block'),
  ('Clutch Kit'),
  ('Compacted Graphite Iron Flat 2 Engine Block'),
  ('Compacted Graphite Iron Flat 4 Engine Block'),
  ('Compacted Graphite Iron Flat 6 Engine Block'),
  ('Compacted Graphite Iron Flat 8 Engine Block'),
  ('Compacted Graphite Iron Four Rotor Rotor Housing'),
  ('Compacted Graphite Iron Inline 3 Engine Block'),
  ('Compacted Graphite Iron Inline 4 Engine Block'),
  ('Compacted Graphite Iron Inline 5 Engine Block'),
  ('Compacted Graphite Iron Inline 6 Engine Block'),
  ('Compacted Graphite Iron Inline 8 Engine Block'),
  ('Compacted Graphite Iron L4 Engine Block'),
  ('Compacted Graphite Iron Single Piston Engine Block'),
  ('Compacted Graphite Iron Single Rotor Rotor Housing'),
  ('Compacted Graphite Iron Three Rotor Rotor Housing'),
  ('Compacted Graphite Iron Twin Rotor Rotor Housing'),
  ('Compacted Graphite Iron V-Twin Engine Block'),
  ('Compacted Graphite Iron V10 Engine Block'),
  ('Compacted Graphite Iron V12 Engine Block'),
  ('Compacted Graphite Iron V16 Engine Block'),
  ('Compacted Graphite Iron V4 Engine Block'),
  ('Compacted Graphite Iron V6 Engine Block'),
  ('Compacted Graphite Iron V8 Engine Block'),
  ('Compacted Graphite Iron W12 Engine Block'),
  ('Compacted Graphite Iron W16 Engine Block'),
  ('Compacted Graphite Iron W18 Engine Block'),
  ('Compacted Graphite Iron W6 Engine Block'),
  ('Compacted Graphite Iron W8 Engine Block'),
  ('Compression Tester'),
  ('Conical Billet Steel Valve Spring Set'),
  ('Conical Cast Steel Valve Spring Set'),
  ('Conical Forged Steel Valve Spring Set'),
  ('Conical Titanium Valve Spring Set'),
  ('Coolant'),
  ('Copper Standard Spark Plug'),
  ('Custom Vehicle Horn'),
  ('Custom Wheel Rims'),
  ('Customized Plates'),
  ('Decal Remover'),
  ('Declasse 3-Speed Transmission (3-speed manual)'),
  ('Declasse 4L80-E Transmission (4-speed auto)'),
  ('Declasse 6L80 Transmission (6-speed auto)'),
  ('Declasse Hydro-Drive 400 (3-speed auto)'),
  ('Declasse M22 Rock Crusher (4-speed manual)'),
  ('Declasse Powerslide Transmission (2-speed auto)'),
  ('Declasse TH400 Transmission (3-speed auto)'),
  ('Differential Fluid'),
  ('Differential Re-Gear Kit'),
  ('Differential Rebuild Kit'),
  ('Dished Billet Aluminum Piston'),
  ('Dished Billet Steel Piston'),
  ('Dished Cast Aluminum Piston'),
  ('Dished Cast Iron Piston'),
  ('Dished Cast Steel Piston'),
  ('Dished Forged Aluminum Piston'),
  ('Dished Forged Steel Piston'),
  ('Dished Powder Metal Piston'),
  ('Dished Titanium Piston'),
  ('Domed Billet Aluminum Piston'),
  ('Domed Billet Steel Piston'),
  ('Domed Cast Aluminum Piston'),
  ('Domed Cast Iron Piston'),
  ('Domed Cast Steel Piston'),
  ('Domed Forged Aluminum Piston'),
  ('Domed Forged Steel Piston'),
  ('Domed Powder Metal Piston'),
  ('Domed Titanium Piston'),
  ('Door Assembly'),
  ('Drag Tire'),
  ('Drift Smoke Tires'),
  ('Drift Tire'),
  ('Drive Belt'),
  ('Drivetrain Part'),
  ('Dual Billet Steel Valve Spring Set'),
  ('Dual Cast Steel Valve Spring Set'),
  ('Dual Forged Steel Valve Spring Set'),
  ('Dual Titanium Valve Spring Set'),
  ('Duct Tape'),
  ('Electric Scrap'),
  ('Electronic Circuit Tester'),
  ('Empty container'),
  ('Engine'),
  ('EV Drive Motor'),
  ('EV Power Inverter'),
  ('EV Traction Battery'),
  ('Exhaust Manifold'),
  ('Exterior Cosmetics'),
  ('Factory Cast Aluminum Cylinder Head'),
  ('Factory Cast Iron Cylinder Head'),
  ('Factory Cast Steel Cylinder Head'),
  ('Factory Forged Aluminum Cylinder Head'),
  ('Factory Forged Steel Cylinder Head'),
  ('Fiberglass Sheet'),
  ('Flashlight'),
  ('Flat Top Billet Aluminum Piston'),
  ('Flat Top Billet Steel Piston'),
  ('Flat Top Cast Aluminum Piston'),
  ('Flat Top Cast Iron Piston'),
  ('Flat Top Cast Steel Piston'),
  ('Flat Top Forged Aluminum Piston'),
  ('Flat Top Forged Steel Piston'),
  ('Flat Top Powder Metal Piston'),
  ('Flat Top Titanium Piston'),
  ('Forged Crankshaft'),
  ('Front Fender'),
  ('Fuel Filter'),
  ('Fuel Pump'),
  ('Fuel Siphon'),
  ('FWD Conversion Kit'),
  ('glass'),
  ('H-Beam Billet Aluminum Connecting Rod'),
  ('H-Beam Billet Steel Connecting Rod'),
  ('H-Beam Cast Aluminum Connecting Rod'),
  ('H-Beam Cast Iron Connecting Rod'),
  ('H-Beam Cast Steel Connecting Rod'),
  ('H-Beam Forged Aluminum Connecting Rod'),
  ('H-Beam Forged Steel Connecting Rod'),
  ('H-Beam Powder Metal Connecting Rod'),
  ('H-Beam Titanium Connecting Rod'),
  ('hammer'),
  ('Head Gasket Set'),
  ('High Voltage Wiring'),
  ('Hood'),
  ('Hydraulic Flat Tappet Set'),
  ('Hydraulic Roller Tappet Set'),
  ('I-Beam Billet Aluminum Connecting Rod'),
  ('I-Beam Billet Steel Connecting Rod'),
  ('I-Beam Cast Aluminum Connecting Rod'),
  ('I-Beam Cast Iron Connecting Rod'),
  ('I-Beam Cast Steel Connecting Rod'),
  ('I-Beam Forged Aluminum Connecting Rod'),
  ('I-Beam Forged Steel Connecting Rod'),
  ('I-Beam Powder Metal Connecting Rod'),
  ('I-Beam Titanium Connecting Rod'),
  ('Internal Cosmetics'),
  ('Iridium Spark Plug'),
  ('Iron Powder'),
  ('Jump Starter'),
  ('Landing Strut'),
  ('Large Centrifugal Supercharger'),
  ('Large Positive Displacement Supercharger'),
  ('lithium'),
  ('Livery Roll'),
  ('MAF Sensor'),
  ('Magnesium Alloy Flat 2 Engine Block'),
  ('Magnesium Alloy Flat 4 Engine Block'),
  ('Magnesium Alloy Flat 6 Engine Block'),
  ('Magnesium Alloy Flat 8 Engine Block'),
  ('Magnesium Alloy Four Rotor Rotor Housing'),
  ('Magnesium Alloy Inline 3 Engine Block'),
  ('Magnesium Alloy Inline 4 Engine Block'),
  ('Magnesium Alloy Inline 5 Engine Block'),
  ('Magnesium Alloy Inline 6 Engine Block'),
  ('Magnesium Alloy Inline 8 Engine Block'),
  ('Magnesium Alloy L4 Engine Block'),
  ('Magnesium Alloy Single Piston Engine Block'),
  ('Magnesium Alloy Single Rotor Rotor Housing'),
  ('Magnesium Alloy Three Rotor Rotor Housing'),
  ('Magnesium Alloy Twin Rotor Rotor Housing'),
  ('Magnesium Alloy V-Twin Engine Block'),
  ('Magnesium Alloy V10 Engine Block'),
  ('Magnesium Alloy V12 Engine Block'),
  ('Magnesium Alloy V16 Engine Block'),
  ('Magnesium Alloy V4 Engine Block'),
  ('Magnesium Alloy V6 Engine Block'),
  ('Magnesium Alloy V8 Engine Block'),
  ('Magnesium Alloy W12 Engine Block'),
  ('Magnesium Alloy W16 Engine Block'),
  ('Magnesium Alloy W18 Engine Block'),
  ('Magnesium Alloy W6 Engine Block'),
  ('Magnesium Alloy W8 Engine Block'),
  ('Mechanic Bench'),
  ('Mechanic Clipboard'),
  ('Mechanic Toolbox'),
  ('Mechanic Toolkit'),
  ('Medium Centrifugal Supercharger'),
  ('Medium Positive Displacement Supercharger'),
  ('Moly-Coated Race Ring Pack'),
  ('Motor Oil (1 Qt)'),
  ('Nitrous Bottle (Refill)'),
  ('Nitrous Kit â€” 100 Shot'),
  ('Nitrous Kit â€” 200 Shot'),
  ('Nitrous Kit â€” 300 Shot'),
  ('Nitrous Kit â€” 50 Shot'),
  ('O2 Sensor'),
  ('OBD-II Scanner'),
  ('Off-Road Suspension'),
  ('Off-Road Tire'),
  ('Oil Filter'),
  ('Oil Pump'),
  ('Performance Camshaft'),
  ('Pfister 7MT Transmission (7-speed manual)'),
  ('Plastic'),
  ('Platinum Spark Plug'),
  ('Pneumatic Shifter'),
  ('Ported & Polished Cast Aluminum Cylinder Head'),
  ('Ported & Polished Cast Iron Cylinder Head'),
  ('Ported & Polished Cast Steel Cylinder Head'),
  ('Ported & Polished Forged Aluminum Cylinder Head'),
  ('Ported & Polished Forged Steel Cylinder Head'),
  ('Race 10-Speed Sequential Transmission (manual)'),
  ('Race 8-Speed Sequential Transmission (manual)'),
  ('Race 9-Speed Sequential Transmission (manual)'),
  ('Race Brake Pads'),
  ('Race Camshaft'),
  ('Race Intercooler'),
  ('Race Radiator'),
  ('Race Suspension'),
  ('Radiator'),
  ('Raw Copper'),
  ('Raw Iron'),
  ('Raw Steel'),
  ('Rear Fender'),
  ('rubber'),
  ('Rusty Shovel'),
  ('RWD Conversion Kit'),
  ('scissors'),
  ('Scrap Metal'),
  ('Seat Cosmetics'),
  ('Signal Booster'),
  ('Small Centrifugal Supercharger'),
  ('Small Positive Displacement Supercharger'),
  ('Solid Flat Tappet Set'),
  ('Solid Roller Tappet Set'),
  ('Sport Brake Pads'),
  ('Sport Radiator'),
  ('Sport Suspension'),
  ('Sport Tire'),
  ('Spray'),
  ('Spray Remover'),
  ('Starter Motor'),
  ('Steel Performance Ring Pack'),
  ('Sticky Tape'),
  ('Stock Brake Pads'),
  ('Stock Intercooler'),
  ('Stock Suspension'),
  ('Stock Tire'),
  ('Stock/Mild Camshaft'),
  ('Street Brake Pads'),
  ('Street Intercooler'),
  ('Street Perf Camshaft'),
  ('Street Radiator'),
  ('Street Tire'),
  ('Subwoofer'),
  ('Suspension Service Part'),
  ('Suspension Springs'),
  ('Sway Bar'),
  ('Synthetic Acid'),
  ('Taillight Assembly'),
  ('Tarmac TR-6060 Transmission (6-speed manual)'),
  ('Thermostat'),
  ('Throttle Position Sensor'),
  ('Timing Belt Kit'),
  ('Timing Chain Kit'),
  ('Timing Gears'),
  ('Tool Box'),
  ('Toolkit'),
  ('Torque Converter'),
  ('Torque/Tow Camshaft'),
  ('Tow Rope'),
  ('Track Tire'),
  ('Transmission Fluid (1 Qt)'),
  ('Transmission Rebuild Kit'),
  ('Tread Depth Gauge'),
  ('Tri-Metal Conrod Bearing'),
  ('Tri-Metal Main Bearing'),
  ('trowel'),
  ('Trunk Lid'),
  ('Turbocharger â€” Large Compressor / Large Turbine'),
  ('Turbocharger â€” Large Compressor / Medium Turbine'),
  ('Turbocharger â€” Large Compressor / Small Turbine'),
  ('Turbocharger â€” Medium Compressor / Large Turbine'),
  ('Turbocharger â€” Medium Compressor / Medium Turbine'),
  ('Turbocharger â€” Medium Compressor / Small Turbine'),
  ('Turbocharger â€” Small Compressor / Large Turbine'),
  ('Turbocharger â€” Small Compressor / Medium Turbine'),
  ('Turbocharger â€” Small Compressor / Small Turbine'),
  ('Underglow LEDS'),
  ('Upgraded Clutch Packs'),
  ('Upgraded Synchronizers'),
  ('Vapid 10R80 Transmission (10-speed auto)'),
  ('Vehicle alarm level 1'),
  ('Vehicle alarm level 2'),
  ('Vehicle alarm level 3'),
  ('Vehicle alarm level 4'),
  ('Vehicle Exhaust'),
  ('Vehicle Extra Part'),
  ('Vehicle Front Bumper'),
  ('Vehicle Grille'),
  ('Vehicle Rear Bumper'),
  ('Vehicle Roof'),
  ('Vehicle Skirts'),
  ('Vehicle Spoiler'),
  ('Vehicle Spray Can'),
  ('Vehicle Wax Kit'),
  ('Vehicle Winch'),
  ('Vintage 2-Speed Crash Box (2-speed manual)'),
  ('Water Pump'),
  ('Window Part'),
  ('Window Tint Kit'),
  ('Windshield'),
  ('X-Beam Billet Aluminum Connecting Rod'),
  ('X-Beam Billet Steel Connecting Rod'),
  ('X-Beam Cast Aluminum Connecting Rod'),
  ('X-Beam Cast Iron Connecting Rod'),
  ('X-Beam Cast Steel Connecting Rod'),
  ('X-Beam Forged Aluminum Connecting Rod'),
  ('X-Beam Forged Steel Connecting Rod'),
  ('X-Beam Powder Metal Connecting Rod'),
  ('X-Beam Titanium Connecting Rod'),
  ('Xenon Headlights'),
  ('Zancudo 8HP Transmission (8-speed auto)'),
  ('Zancudo 9HP Transmission (9-speed auto)')
)
select input.name as unmatched_name
from input
left join catalogue_items ci
  on replace(replace(lower(ci.name), chr(8211), '-'), chr(8212), '-')
   = replace(replace(lower(input.name), chr(8211), '-'), chr(8212), '-')
where ci.id is null
order by input.name;
